trigger:
- main

pool:
  name: bhaweshnew

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'SPN_Bhawesh'
    backendAzureRmOverrideSubscriptionID: '9f199aee-1ad7-464f-bd74-4b88ef990086'
    backendAzureRmResourceGroupName: 'stg_rg'
    workingDirectory: '$(System.DefaultWorkingDirectory)/parent'
    backendAzureRmStorageAccountName: 'backednstg'
    backendAzureRmContainerName: 'bhawesh-tfstate'
    backendAzureRmKey: 'aks.tfstate'

# - task: TerraformTask@5
#   inputs:
#     provider: 'azurerm'
#     command: 'plan'
#     workingDirectory: '$(System.DefaultWorkingDirectory)/parent'
#     environmentServiceNameAzureRM: 'SPN_Bhawesh'

# - task: TerraformTask@5
#   inputs:
#     provider: 'azurerm'
#     command: 'apply'
#     workingDirectory: '$(System.DefaultWorkingDirectory)/parent'
#     commandOptions: '-auto-approve'
#     environmentServiceNameAzureRM: 'SPN_Bhawesh'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'destroy'
    workingDirectory: '$(System.DefaultWorkingDirectory)/parent'
    environmentServiceNameAzureRM: 'SPN_Bhawesh'



