
trigger:
 none
#  branches:
#    include:
#      - feature/*
#      - main

variables:
  terraformWorkingDir: '$(System.DefaultWorkingDirectory)/parent'
  azureServiceConnection: 'SPN_Bhawesh'

jobs:
  - job: terraform 
    displayName: Terraform Install and Plan
    pool : bhaweshnew
    
    
    steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(terraformWorkingDir)'
          backendServiceArm: 'SPN_Bhawesh'
          backendAzureRmResourceGroupName: 'G20_RG'
          backendAzureRmStorageAccountName: 'g20stg'
          backendAzureRmContainerName: 'bhawesh-tfstate'
          backendAzureRmKey: 'aks.tfstate'

      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: '$(terraformWorkingDir)'
          environmentServiceNameAzureRM: 'SPN_Bhawesh'

