trigger:
  none
  # branches:
  #   include:
  #     - feature/*
  #     - main
variables:
  terraformWorkingDir: '$(System.DefaultWorkingDirectory)/parent'
  azureServiceConnection: 'SPN_Bhawesh'
jobs:
- job: TerraformInitPlan
  displayName: Terraform Init and Plan
  pool:
    name: bhaweshnew

  steps:
    - checkout: self

    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(terraformWorkingDir)'
        backendServiceArm: '$(azureServiceConnection)'
        backendAzureRmResourceGroupName: 'G20_RG'
        backendAzureRmStorageAccountName: 'g20stg'
        backendAzureRmContainerName: 'bhawesh-tfstate'
        backendAzureRmKey: 'aks.tfstate'

    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(terraformWorkingDir)'
        environmentServiceNameAzureRM: '$(azureServiceConnection)'

- job: ManualValidation
  displayName: Manual Approval Step
  dependsOn: TerraformInitPlan
  pool:
    name: server

  steps:
    - task: ManualValidation@1
      inputs:
        notifyUsers: 'bhawesh.mishra@reewasolutions.com'
        approvers: 'bhawesh.mishra@reewasolutions.com'
        instructions: 'pass kar dena'

- job: TerraformApply
  displayName: Terraform Apply
  dependsOn: ManualValidation
  pool:
    name: bhaweshnew

  steps:
    - checkout: self

    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      displayName: Terraform Apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(terraformWorkingDir)'
        commandOptions: '-auto-approve'
        environmentServiceNameAzureRM: '$(azureServiceConnection)'
