trigger:
- main

pool:
  name: bhaweshnew

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'SPN_Bhawesh'
    backendAzureRmStorageAccountName: 'backednstg'
    backendAzureRmContainerName: 'bhawesh-tfstate'
    backendAzureRmKey: 'aks.tfstate'
