trigger: none

pool: bhaweshnew


steps :

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'


- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/parent'
    backendServiceArm: 'SPN_Bhawesh'
    backendAzureRmStorageAccountName: 'stg_rg'
    backendAzureRmContainerName: bhawesh.tfstate
    backendAzureRmKey: aks.tfstate

