# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: bhaweshnew

steps:
  - 
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

steps:
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'SPN_Bhawesh'
    backendAzureRmStorageAccountName: 'backednstg'
    backendAzureRmContainerName: 'bhawesh-tfstate'
    backendAzureRmKey: 'aks.tfstate'
